### ISSUE TITLE
Sobre estaticidad o dinamicidad del juego o deporte

### ISSUE THREAD

**Issue by abitbetter** [josealber84/explorando-ideas#3]
De manera muy breve se me ha venido a la mente que entonces tal vez por donde haya que comenzar sea por los aspectos más estáticos.  Por ejemplo zonas de juego de un determinado jugador o tratar de capturar jugadas ensayadas.  Sigue siendo muy complicado, pero según vayamos desgranando seguro que encontramos una vía para cuantificarlo.

**Comment by josealberto-arcos-sanchez** [comment]
### Carlos

En cuanto al deporte y los datos tengo una enmienda a la totalidad que quiero plantearos. Para ello usare tres deportes, beisbol, baloncesto y futbol. Beisbol, en el que las estadisticas han funcionado, es un deporte muy estatico y muy repetivo. Un jugador lanza la bola siempre desde la misma posición y esta en bateada también siempre desde la misma posición. La unica variacion en el juego es cuantos corredores hay actualmente en las bases. Esta situacion se repetite durante todo el partido

Baloncesto, en el que parece que las estadisticas estan funcionando, es un deporte menos estatico pero todavía repetitivo. Los jugadores lanzan desde distantas posiciones, se pasan el balon,... Pero sigue siendo repetitivo en el sentido de que las posesiones se repiten cada 24 segundos.

Futbol, es posiblemente igual de poco estatico que el futbol..pero es mucho menos repetitivo. Con esto solo quiere hacer notar la complejidad de encontrar patrones en el futbol.

**Comment by josealberto-arcos-sanchez** [comment]
Estoy de acuerdo a medias. Creo que el fútbol es muy repetitivo, aunque los eventos no sean tan simples como en el baseball. Me explico. 

Está claro que hay muchos más grados de libertad en fútbol que en baseball, por lo que harían falta muchos más datos para obtener conclusiones igual de significativas. 

En comparación con el basket, en fútbol se repiten mucho menos los "eventos de puntuación"  (hay muchos menos goles que canastas). Mismo problema. 

Pero aun así, el fútbol es muy repetitivo si elegimos el punto de vista adecuado. Todos los equipos siguen patrones muy marcados,  tanto al atacar como al defender. Ejemplo: el jugador A coge la pelota en la zona B. El defensor más cercano está a una distancia R y hay X jugadores del equipo contrario entre él y la portería. El 30% de las veces pasa la pelota al jugador E. El 20% de las veces avanza unos metros con la pelota. El 18% de las veces pasa el balón al jugador D. El 5% de las veces tira a puerta... 

Para cada una de las posibilidades, hay un porcentaje de resultados muy positivos (la jugada acaba en gol), algunos resultados positivos (se consigue un corner, un remate a puerta,...),  un porcentaje de negativos (se pierde el balón) y un porcentaje de muy negativos (se produce un contra ataque,  etc). 

Este tipo de eventos ocurre continuamente, y basta con analizar el resultado de cada evento a "largo plazo"  para encontrar patrones de jugadas que optimizan las probabilidades de marcar. Me recuerda un poco al problema del ajedrez, donde se evalúan jugadas aparentemente inocuas en función del desenlace 10 movimientos más tarde. 

Esto es hablar por hablar, claro 😅
Hasta que no nos metamos con profundidad no podemos saber si esto es cierto. Pero intuitivamente parece que es viable encontrar los "caminos hacia el gol" de un equipo, o los "agujeros en defensa" de otro.

**Comment by doncarlangas** [comment]
Jose Alberto, te lo compro (a medias) . Lo que finalmente ha decido la balanza ha sido la expresión los  "caminos hacia el gol" con eso me has ganado.

Si queréis podemos cerrar este issue

**Comment by josealberto-arcos-sanchez** [comment]
Jajaja 👍
